import generateAlign from "./generators/align";
import generateBase from "./generators/base";
import generateBg from "./generators/bg";
import generateBorder from "./generators/border";
import generateBox from "./generators/box";
import generateClear from "./generators/clear";
import generateContainer from "./generators/container";
import generateDisplay from "./generators/display";
import generateDivide from "./generators/divide";
import generateFlex from "./generators/flex";
import generateFloat from "./generators/float";
import generateForm from "./generators/form";
import generateGradient from "./generators/gradient";
import generateGrid from "./generators/grid";
import generateHeight from "./generators/height";
import generateInteractivity from "./generators/interactivity";
import generateJustify from "./generators/justify";
import generateLeading from "./generators/leading";
import generateList from "./generators/list";
import generateMargin from "./generators/margin";
import generateObject from "./generators/object";
import generateOpacity from "./generators/opacity";
import generateOverflow from "./generators/overflow";
import generateOverscroll from "./generators/overscroll";
import generatePadding from "./generators/padding";
import generatePlace from "./generators/place";
import generatePlaceholder from "./generators/placeholder";
import generatePosition from "./generators/position";
import generateShadow from "./generators/shadow";
import generateSpace from "./generators/space";
import generateTable from "./generators/table";
import generateText from "./generators/text";
import generateTracking from "./generators/tracking";
import generateVisibility from "./generators/visibility";
import generateWidth from "./generators/width";
import generateZIndex from "./generators/zindex";

module.exports.generateAlign = generateAlign;
module.exports.generateBase = generateBase;
module.exports.generateBg = generateBg;
module.exports.generateBorder = generateBorder;
module.exports.generateBox = generateBox;
module.exports.generateClear = generateClear;
module.exports.generateContainer = generateContainer;
module.exports.generateDisplay = generateDisplay;
module.exports.generateDivide = generateDivide;
module.exports.generateFlex = generateFlex;
module.exports.generateFloat = generateFloat;
module.exports.generateForm = generateForm;
module.exports.generateGradient = generateGradient;
module.exports.generateGrid = generateGrid;
module.exports.generateHeight = generateHeight;
module.exports.generateInteractivity = generateInteractivity;
module.exports.generateJustify = generateJustify;
module.exports.generateLeading = generateLeading;
module.exports.generateList = generateList;
module.exports.generateMargin = generateMargin;
module.exports.generateObject = generateObject;
module.exports.generateOpacity = generateOpacity;
module.exports.generateOverflow = generateOverflow;
module.exports.generateOverscroll = generateOverscroll;
module.exports.generatePadding = generatePadding;
module.exports.generatePlace = generatePlace;
module.exports.generatePlaceholder = generatePlaceholder;
module.exports.generatePosition = generatePosition;
module.exports.generateShadow = generateShadow;
module.exports.generateSpace = generateSpace;
module.exports.generateTable = generateTable;
module.exports.generateText = generateText;
module.exports.generateTracking = generateTracking;
module.exports.generateVisibility = generateVisibility;
module.exports.generateWidth = generateWidth;
module.exports.generateZIndex = generateZIndex;
