const variants = {
  accentColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  accessibility: ["hover", "focus"],
  aspect: ["hover", "focus"],
  backgroundColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  blur: ["hover", "focus"],
  borderColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  boxShadow: ["hover", "focus"],
  brightness: ["hover", "focus"],
  caretColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  contrast: ["hover", "focus"],
  dropShadow: ["hover", "focus"],
  fill: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  flexBasis: ["hover", "focus"],
  gradientColorStops: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  grayscale: ["hover", "focus"],
  hueRotate: ["hover", "focus"],
  insetRing: ["hover", "focus"],
  insetShadow: ["hover", "focus"],
  invert: ["hover", "focus"],
  opacity: ["hover", "focus"],
  outlineColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  outlineOffset: ["hover", "focus"],
  outlineStyle: ["hover", "focus"],
  outlineWidth: ["hover", "focus"],
  placeholderColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  ringColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  ringOffsetColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  ringOffsetWidth: ["hover", "focus"],
  ringWidth: ["hover", "focus"],
  rotate: ["hover", "focus"],
  saturate: ["hover", "focus"],
  scale: ["hover", "focus"],
  sepia: ["hover", "focus"],
  skew: ["hover", "focus"],
  stroke: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  strokeWidth: ["hover", "focus"],
  textColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  textDecoration: ["focus", "hover"],
  textDecorationColor: ["focus", "hover", "not-hover", "not-focus", "not-disabled"],
  textDecorationStyle: ["focus", "hover"],
  textDecorationThickness: ["focus", "hover"],
  textShadowBlur: ["hover", "focus"],
  textShadowColor: ["hover", "focus", "not-hover", "not-focus", "not-disabled"],
  textShadowOpacity: ["hover", "focus"],
  textShadowX: ["hover", "focus"],
  textShadowY: ["hover", "focus"],
  touchAction: ["hover", "focus"],
  mask: ["hover", "focus"],
  transform3d: ["hover", "focus"],
  translate: ["hover", "focus"],
  zIndex: ["hover", "focus"],
};

export default variants;
